apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: rnk-expense-vol
spec:
  selector:
    app: backend
    tier: backend
    project: expense-vol
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}